---
title: "form x function"
output: html_document
date: "2024-01-26"
---

```{r setup, include=FALSE}
library(tidyverse)
library(childesr)
library(here)
library(patchwork)
library(ggthemes)
library(igraph)
library(statnet)
library(entropy)
library(philentropy)
library(ggthemes)
library(ggalluvial)
library(feather)
library(udpipe)
library(stats)
library(ggrepel)
library(ggthemes)
library(scales)
library(viridis)
library(artists)
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE)
```

```{r read-data}
ldp_raw <- read_csv(here("data/ldp_speech_acts.csv"))
act_codes <- read.csv(here("act_codes.csv"))
measures <- read_feather(here("data/measures.feather")) %>%
  mutate(age_months = 14 + (as.numeric(visit) - 1)*4)

subj_info <- read_csv(here("ldp_subject_info.csv")) %>%
  mutate(tbi_status = if_else(!is.na(lesion), "traumatic_brain_injury", "typically_developing"))

adjacency_pairs <- read_csv(here("adjacency_pairs_contingency.csv"))

epsilon = 0.000000000001

ldp_acts <- ldp_raw %>%
  arrange(utterance_id) %>%
  rename(act_code = speech_act) %>%
  left_join(act_codes, by = "act_code") %>%
  left_join(subj_info %>% select(id, tbi_status), by = c("child_id" = "id")) %>%
  # only include typically developing kids (excludes kids with a traumatic brain injury)
  filter(tbi_status == "typically_developing") %>%
  group_by(child_id, age_months) %>%
  mutate(prior_act = lag(meaning),
         prior_act_code = lag(act_code),
         lag_speaker = lag(speaker_code)) %>%
  ungroup() %>%
  left_join(adjacency_pairs %>% select(source, target, contingency), 
  by = c("prior_act_code" = "source", "act_code" = "target")) %>%
  mutate(utterance = gsub(" '", " ", tokens)) %>%
  mutate(utterance = gsub("',", "", utterance)) %>%
  mutate(utterance = gsub("'\\]", "", utterance)) %>%
  mutate(utterance = gsub("\\['", "", utterance)) %>%
  mutate(utterance = gsub(" \"", " ", utterance)) %>%
  mutate(utterance = gsub("\",", "", utterance)) %>%
  mutate(utterance = gsub("\"\\]", "", utterance)) %>%
  mutate(utterance = gsub("\\[\"", "", utterance)) %>%
  mutate(utterance = trimws(utterance)) %>%
  mutate(meaning = trimws(meaning)) %>%
  mutate(utterance = str_replace_all(trimws(str_remove_all(utterance, "[&.?#!+]")), 
                                     "  ", " "))

enough_data_sessions <- ldp_acts %>%
  group_by(child_id, age_months, speaker_code) %>%
  count() %>%
  pivot_wider(names_from = speaker_code, values_from = n) %>%
  filter(CHI >= 10, ADU >= 10) %>%
  mutate(id_session = paste(child_id, age_months, sep = "_"))

ldp_acts <- ldp_acts %>%
  mutate(id_session = paste(child_id, age_months, sep = "_")) %>%
  filter(id_session %in% enough_data_sessions$id_session)

common_acts <- ldp_acts %>%
  count(meaning) %>%
  arrange(desc(n)) %>%
  slice(1:20) 

common_words <- ldp_acts %>%
  mutate(word = strsplit(utterance, " ")) %>% 
  unnest(word) %>%
  group_by(word) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  arrange(desc(n)) %>%
  slice(1:150)

entropies <- read_csv(here("data/child_act_entropies.csv"))
```

```{r parse, eval = FALSE}
udmodel <- udpipe_load_model(file = "english-ewt-ud-2.4-190531.udpipe")

get_parse <- function(txt) {
  parses <- txt %>%
    udpipe(., udmodel, parallel.cores = 4) %>%
    as_tibble() %>%
    mutate(parse = if_else(token %in% common_words$word, token, upos),
           parse = if_else((token == "'s" & upos == "PART"), upos, parse))

  return(paste(parses$parse, collapse = " "))
}

vget_parse <- Vectorize(get_parse)

parsed_utts <- ldp_acts %>%
  rowwise() %>%
  mutate(frame = vget_parse(utterance)) %>%
  ungroup() %>%
  select(utterance_id, transcript_file, child_id, age_months, tokens, pos,
         speaker_code, tbi_status, utterance, frame) %>%
  arrange(utterance_id)

#write_csv(parsed_utts, here("data/ldp_frames.csv"))

```

```{r}
parsed_utts <- read_csv(here("data/ldp_frames.csv"))

ldp_acts_frames <- ldp_acts %>%
  left_join(parsed_utts)

include_frames <- ldp_acts_frames %>%
  count(frame) %>%
  arrange(desc(n)) %>%
  filter(n > 10)

common_frames <- ldp_acts_frames %>%
  count(frame) %>%
  arrange(desc(n)) %>%
  slice(1:30)

common_acts <- ldp_acts_frames %>%
  count(meaning) %>%
  arrange(desc(n)) %>%
  slice(1:20)

act_entropies <- ldp_acts_frames %>%
  group_by(child_id, age_months, speaker_code) %>%
  count(meaning) %>%
  ungroup() %>%
  complete(child_id, speaker_code, age_months, meaning) %>%
  replace_na(list("n" = 0)) %>%
  group_by(child_id, age_months, speaker_code) %>%
  summarise(entropy = entropy(n, unit = "log2")) %>%
  ungroup()

frame_entropies <- ldp_acts_frames  %>%
  filter(frame %in% include_frames$frame) %>%
  group_by(child_id, age_months, speaker_code) %>%
  count(frame) %>%
  ungroup() %>%
  complete(child_id, speaker_code, age_months, frame) %>%
  replace_na(list("n" = 0)) %>%
  group_by(child_id, age_months, speaker_code) %>%
  summarise(frame_entropy = entropy(n, unit = "log2")) %>%
  ungroup() %>%
  left_join(act_entropies %>% rename("comm_act_entropy" = "entropy"))

frame_act <- ldp_acts_frames %>%
  filter(frame %in% include_frames$frame) %>%
  group_by(age_months, speaker_code) %>%
  count(meaning, frame) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup()

frame_act %>%
  filter(meaning %in% common_acts$meaning,
         frame %in% common_frames$frame) %>%
  ungroup() %>%
  ggplot(aes(fill = log(prob), x = meaning, y = frame)) +
  geom_tile() +
  facet_grid(speaker_code~age_months) +
  viridis::scale_fill_viridis() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
form_function_joint_all <- ldp_acts_frames %>%
  count(frame, meaning) %>%
  mutate(prob = n/sum(n)) %>%
  arrange(desc(prob)) %>%
  ungroup() 

top_multiword <- form_function_joint_all %>%
  mutate(utt_length = lengths(str_split(frame, " "))) %>%
  filter(utt_length >= 2)

form_function_joint <- ldp_acts_frames %>%
  filter(frame %in% include_frames$frame) %>%
  group_by(age_months, speaker_code) %>%
  count(frame, meaning) %>%
  mutate(n = n + epsilon,
         prob = n/sum(n)) %>%
  ungroup()

form_function_joint_by_child <- ldp_acts_frames %>%
  filter(frame %in% include_frames$frame) %>%
  group_by(child_id, age_months, speaker_code) %>%
  count(frame, meaning) %>%
  mutate(n = n + epsilon,
         prob = n/sum(n)) %>%
  ungroup()

get_mis <- function(joint_probs_normed) {
  
  act_marginal <- joint_probs_normed %>%
    group_by(age_months, speaker_code, meaning) %>%
    summarise(act_prob = sum(prob)) %>% ungroup()
  
  frame_marginal <- joint_probs_normed %>%
    group_by(age_months, speaker_code, frame) %>%
    summarise(frame_prob = sum(prob)) %>% ungroup()
  
  all_probs <- joint_probs_normed %>%
    rename(joint_prob = prob) %>%
    left_join(act_marginal, 
              by = c("age_months", "speaker_code", "meaning")) %>%
    left_join(frame_marginal, 
              by = c("age_months", "speaker_code", "frame"))
  
  parent <- all_probs %>%
    filter(speaker_code == "ADU") %>%
    mutate(term = joint_prob * log2(joint_prob/(act_prob * frame_prob))) %>%
    group_by(age_months) %>%
    summarise(mi = sum(term)) %>%
    mutate(type = "parent")
  
  child <- all_probs %>%
    filter(speaker_code == "CHI") %>%
    mutate(term = joint_prob * log2(joint_prob/(act_prob * frame_prob))) %>%
    group_by(age_months) %>%
    summarise(mi = sum(term)) %>%
    mutate(type = "child")

  
  all_mis <- rbind(child, parent)
  return(all_mis)
}

get_mis_by_child <- function(joint_probs_normed) {
  
  act_marginal <- joint_probs_normed %>%
    group_by(child_id, age_months, speaker_code, meaning) %>%
    summarise(act_prob = sum(prob)) %>% ungroup()
  
  frame_marginal <- joint_probs_normed %>%
    group_by(child_id, age_months, speaker_code, frame) %>%
    summarise(frame_prob = sum(prob)) %>% ungroup()
  
  all_probs <- joint_probs_normed %>%
    rename(joint_prob = prob) %>%
    left_join(act_marginal, 
              by = c("child_id", "age_months", "speaker_code", "meaning")) %>%
    left_join(frame_marginal, 
              by = c("child_id", "age_months", "speaker_code", "frame"))
  
  parent <- all_probs %>%
    filter(speaker_code == "ADU") %>%
    mutate(term = joint_prob * log2(joint_prob/(act_prob * frame_prob))) %>%
    group_by(child_id, age_months) %>%
    summarise(mi = sum(term)) %>%
    mutate(type = "parent") %>%
    ungroup()
  
  child <- all_probs %>%
    filter(speaker_code == "CHI") %>%
    mutate(term = joint_prob * log2(joint_prob/(act_prob * frame_prob))) %>%
    group_by(child_id, age_months) %>%
    summarise(mi = sum(term)) %>%
    mutate(type = "child") %>%
    ungroup()

  
  all_mis <- rbind(child, parent)
  return(all_mis)
}

mis <- get_mis(form_function_joint)
mis_by_child <- get_mis_by_child(form_function_joint_by_child)

mis %>%
  ggplot(aes(x = age_months, y = mi, color = type)) +
  geom_smooth()

mi_annotations <- tibble(age_months = c(16, 16), 
                         type = c("child", "parent"),
                         percent_explained = c(.44, .86))

mis_by_child %>%
  ggplot(aes(x = age_months, y = mi, color = type)) +
  geom_jitter(width = 0.8, height = 0, alpha = 0.3) +
  geom_smooth() +
  xlab("Age in months") +
  ylab("Mutual information between syntactic frames \n and communicative acts") +
  scale_color_manual(values = c("#be6b7b", "#8395b6")) +
  theme_few()+
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank())

mi_annotations <- tibble(age_months = c(16, 16), 
                         type = c("child", "parent"),
                         percent_explained = c(.44, .86))

mis_by_child %>%
  mutate(speaker_code = if_else(type == "child", "CHI", "ADU")) %>%
  left_join(entropies, by = c("child_id", "age_months", "speaker_code")) %>%
  mutate(percent_explained = mi/entropy) %>%
  ggplot(aes(x = age_months, y = percent_explained, color = type, label = type)) +
  geom_jitter(width = 0.8, height = 0, alpha = 0.3) +
  geom_smooth() +
  xlab("Age in months") +
  ylab("Proportion of communicative act entropy \n explained by syntactic frame") +
  scale_color_manual(values = c("#be6b7b", "#8395b6")) +
  scale_color_manual(values = c("#be6b7b", "#8395b6")) +
  theme_few()+
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.text=element_text(size=12),
    axis.title=element_text(size=14,face="bold")) +
  geom_label(aes(label = type), data = mi_annotations, size = 5)


mis_by_child %>%
  mutate(speaker_code = if_else(type == "child", "CHI", "ADU")) %>%
  left_join(entropies, by = c("child_id", "age_months", "speaker_code")) %>%
  mutate(percent_explained = mi/entropy) %>%
  group_by(age_months, speaker_code) %>%
  summarise(mean(percent_explained))
```

```{r}
frame_repertoire <- ldp_acts_frames %>%
  group_by(child_id, age_months, speaker_code) %>%
  count(frame) %>%
  summarise(frame_entropy = entropy(n, unit = "log2")) %>%
  ungroup() %>%
  left_join(entropies %>% rename("comm_act_entropy" = "entropy"))

average_frame_act_ents <- frame_repertoire %>%
  group_by(child_id, speaker_code) %>%
  summarise(mean_act_ent = mean(comm_act_entropy),
            mean_frame_ent = mean(frame_entropy)) %>%
  ungroup()

ggplot(frame_repertoire, aes(x = age_months, y = frame_entropy, color = speaker_code)) +
  geom_point() +
  geom_smooth()

ggplot(frame_repertoire, aes(x = comm_act_entropy, y = frame_entropy, group = speaker_code)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~speaker_code)

ggplot(average_frame_act_ents, aes(x = mean_act_ent, y = mean_frame_ent, group = speaker_code)) + 
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~speaker_code)

child_frame_acts <- average_frame_act_ents %>% filter(speaker_code == "CHI")
cor.test(child_frame_acts$mean_act_ent, child_frame_acts$mean_frame_ent)

all_frame_act_cors <- frame_repertoire %>%
  group_by(age_months) %>%
  summarise(cor = cor.test(frame_entropy, comm_act_entropy)$estimate, 
            p = cor.test(frame_entropy, comm_act_entropy)$p.value)

mean(all_frame_act_cors$cor)
```
