---
title: "LDP_Analyses"
author: "misha !"
date: "2023-11-14"
output: html_document
---

Load libraries
```{r}
library(tidyverse)
library(childesr)
library(here)
library(patchwork)
library(ggthemes)
library(ggplot2)
```

Load Speech Acts
```{r}
ldp_speech_acts <- read.csv("/Users/michaelokeeffe/Documents/SoIL/Fall 2023/ldp_speech_acts_deidentified.csv")
colnames(ldp_speech_acts)[colnames(ldp_speech_acts) == "y_pred"] <- "act_code"
act_codes <- read_csv(here("act_codes.csv"))
```

Left Join
```{r}
ldp_speech_acts <- ldp_speech_acts %>%
  left_join(act_codes, by="act_code")
```



Rainbow Plot

```{r rep-plot}
common_acts <- ldp_speech_acts %>%
  count(act_code, meaning) %>%
  arrange(desc(n)) %>%
  slice(1:60)

labels <- c("agree to act", "agree with proposition", "answer affirmative", "answer calls", "ask wh- question", "ask wh- question", "ask yes/no question", "ask yes/no question", "declarative statement", "declarative statement", "mark event", "mark event", "no clear function", "prohibition", "propose action", "propose action", "repetition", "state intent", "answer wh- question", "question about other's wishes")

branching_annotations <- tibble(meaning = 1:20,
                                meaning_name = labels,
                                age_bin = c(36, 32, 36, 46, 44, 48, 50, 44, 36,
                                            36, 20, 53, 22, 50, 38, 24, 21, 36, 
                                            38, 40),
                                n = c(.99, .97, .93, .9, .86, .845, .785, 
                                      .7, .65, .45, .30, .39,
                                      .31, .22, .24, .14, .12, .10, .04, .02),
                                speaker_role = c("Child","Parent","Child","Parent","Parent","Child","Child","Parent","Child","Parent","Parent","Child","Child","Parent","Child","Parent","Child","Child","Child","Parent"))
  
branching <- ldp_speech_acts %>%
  filter(act_code %in% common_acts$act_code) %>%
  mutate(age_months = as.numeric(age_months),
         age_bin = cut(age_months, 20, labels = FALSE),
         age_bin = (44/20)*age_bin + 14,
         speaker_role = if_else(speaker == "CHI", "Child", "Parent"),
         speaker_role = factor(speaker_role, levels = c("Child", "Parent"))) %>%
  group_by(age_bin, speaker_role) %>%
  count(meaning) 



ggplot(branching, aes(x = age_bin, y = n, group = meaning, 
             fill = as.factor(meaning))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker_role) +
  theme_few(base_size = 10) +
  #theme(legend.position = "none") + 
  #geom_text(aes(label = meaning_name), size = 3, color = "white", hjust = 1,
   #         fontface = "bold",data = branching_annotations) +
  labs(x = "Age (months)", y = "Communicative act proportion")+
  theme(axis.title.x=element_text(size=15,face="bold"),
        axis.title.y=element_text(size=15,face="bold"),
        strip.text.x=element_text(size=15,face="bold"))

#ggsave(branching_plot, filename = "plots/branching_plot.png",  width = 9, height = 5, units = "in", dpi = 300, bg = "transparent")
```
```

