---
title: "Form and function"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(tidyboot)
library(ggthemes)
library(feather)
library(childesr)
library(vroom)
library(knitr)
library(ggalluvial)
library(cluster)
library(ClusterR)
library(skmeans)
library(Matrix)
library(irlba)
library(factoextra)

theme_set(theme_few(base_size = 10))
epsilon = 0.00001
```

```{r read-data, message = FALSE, warning=FALSE}
ldp <- read_feather(here("data/ldp_parsed_frames.feather"))
act_codes <- read_csv(here("data/act_codes.csv"))
speech_acts <- read_csv(here("data/speech_acts_ldp.csv")) %>%
  mutate(child_id = sub("\\_.*", "", file_id),
         transcript_id = sub(".*\\_", "", file_id),
         index = index + 1,
         child_id = as.numeric(child_id)) %>%
  left_join(act_codes, by = c("y_pred" = "act_code"))
ldp <- ldp %>%
  left_join(speech_acts %>% select(index, file_id, child_id, transcript_id, y_pred, meaning), 
            by = c("index", "file_id", "child_id"))

n_transcripts <- ldp %>%
  select(file_id) %>%
  distinct(file_id) %>%
  nrow()

n_children <- ldp %>%
  select(child_id) %>%
  distinct(child_id) %>%
  nrow()
#104 children -- includes children with traumatic brain injury

```

```{r, message = FALSE}
frame_freqs <- ldp %>%
  count(utt_parse) %>%
  arrange(desc(n)) %>%
  mutate(num_tokens = str_count(str_remove_all(utt_parse, "[,.!?']"),"\\S+")) 

act_freqs <- ldp %>%
  count(meaning, y_pred) %>%
  arrange(desc(n))

act_freqs %>%
  kable()

top_frames <- frame_freqs %>%
  slice(1:50) 

top_frames %>%
  kable()

frames <- ldp %>%
  mutate(age_bin = cut(age_months, 20, labels = FALSE),
         age_bin = (54/20)*age_bin + 6,
         speaker_role = if_else(speaker == "CHI", "Child", "Parent"),
         speaker_role = factor(speaker_role, levels = c("Child", "Parent"))) %>%
  count(speaker_role, utt_parse, age_bin)

frames %>%
  filter(utt_parse %in% top_frames$utt_parse) %>%
  ggplot(aes(x = age_bin, y = n, group = utt_parse, 
             fill = as.factor(utt_parse))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker_role) +
  labs(x = "Age (months)", y = "Frame proportion")
```

Top frames over development.

```{r, message = FALSE}
multiword_frames <- frame_freqs %>%
  filter(num_tokens > 1) %>%
  slice(1:25) 

frames %>%
  filter(utt_parse %in% multiword_frames$utt_parse) %>%
  ggplot(aes(x = age_bin, y = n, group = utt_parse, 
             fill = as.factor(utt_parse))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker_role) +
  labs(x = "Age (months)", y = "Frame proportion")
```

Top frames with more than one word over development.

```{r, message = FALSE}
three_plus_word_frames <- frame_freqs %>%
  filter(num_tokens > 3) %>%
  slice(1:25) 

three_plus_word_frames %>%
  kable()

frames %>%
  filter(utt_parse %in% three_plus_word_frames$utt_parse) %>%
  ggplot(aes(x = age_bin, y = n, group = utt_parse, 
             fill = as.factor(utt_parse))) +
  geom_area(position = "fill", color = "black") +
  facet_wrap(~speaker_role) +
  labs(x = "Age (months)", y = "Frame proportion")
```

Top frames with more than three words over development.

```{r, message = FALSE}
top_frames <- frame_freqs %>%
  slice(1:40)

top_acts <- act_freqs %>%
  slice(1:40)

frames_x_acts <- ldp %>%
  filter(utt_parse %in% top_frames$utt_parse) %>%
  filter(y_pred %in% top_acts$y_pred) %>%
  count(speaker, utt_parse, meaning)

frames_x_acts %>%
  group_by(utt_parse) %>%
  mutate(prob = n/sum(n)) %>%
  ungroup() %>% 
  ggplot(aes(x=meaning, y=utt_parse, fill=log(prob))) + 
  geom_tile() +
  facet_wrap(~speaker, scales = "free") +
  viridis::scale_fill_viridis() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.4, hjust = 1))

frames_x_acts %>%
  arrange(desc(n)) %>%
  kable()

```


```{r anti_frames}
get_anti_frame <- function(tokens, frame) {
  split_gloss = unlist(strsplit(tokens, " "))
  split_frame = unlist(strsplit(frame, " "))
  anti_frame <- split_gloss[!split_gloss %in% split_frame]
  return(paste(unlist(anti_frame), collapse=' '))
}
get_anti_frame <- Vectorize(get_anti_frame)

left_out = c("don't", "that's", "it's", "I'm", "what's", "you're", "let's", "he's", "can't", "I'll", "there's", "where's", "we're", "who's")

ldp <- ldp %>%
  mutate(anti_frame = get_anti_frame(tokens, utt_parse)) %>%
  mutate(anti_frame = str_remove(anti_frame, "^.*(don't|that's|it's|I'm|what's|you're|let's|he's|can't|I'll|there's|where's|we're|who's).*$")) %>%
  mutate(anti_frame = trimws(anti_frame))

frame_x_anti_frame <- ldp %>%
  mutate(num_tokens = str_count(str_remove_all(utt_parse, "[,.!?']"),"\\S+"))  %>%
  filter(num_tokens > 1, anti_frame != "") %>%
  count(utt_parse, anti_frame) %>%
  arrange(desc(n))

frame_slot_age <- ldp %>%
  mutate(num_tokens = str_count(str_remove_all(utt_parse, "[,.!?']"),"\\S+"))  %>%
  filter(num_tokens > 1, anti_frame != "") %>%
  count(age_months, utt_parse, anti_frame) %>%
  arrange(desc(n))
```

```{r alluvial}
ggplot(frame_x_anti_frame %>% filter(n > 100),
       aes(y = n, axis1 = utt_parse, axis2 = anti_frame)) +
  geom_alluvium(aes(fill = utt_parse)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Frame", "Slot")) + 
  theme(legend.position = "none") 

ggplot(frame_slot_age %>% filter(n > 20),
       aes(y = n, axis1 = utt_parse, axis2 = anti_frame, group = age_months)) +
  geom_alluvium(aes(fill = utt_parse)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Frame", "Slot")) + 
  theme(legend.position = "none") +
  facet_wrap(~age_months, scales = "free")
```


```{r common_sequences}
sequences <- ldp %>%
  mutate(next_utt = lead(tokens),
         next_next_utt = lead(tokens, n = 2),
         next_act = lead(meaning),
         next_next_act = lead(meaning, n = 2),
         next_frame = lead(utt_parse),
         next_next_frame = lead(utt_parse, n = 2))

utt_sequences <- sequences %>%
  group_by(age_months, tokens, next_utt, next_next_utt) %>%
  count() %>%
  arrange(age_months, desc(n))

act_sequences <- sequences %>%
  group_by(age_months, meaning, next_act, next_next_act) %>%
  count() %>%
  arrange(age_months, desc(n))

frame_sequences <- sequences %>%
  group_by(age_months, utt_parse, next_frame, next_next_frame) %>%
  count() %>%
  arrange(age_months, desc(n))
```

```{r alluvial}
ggplot(frame_sequences %>% filter(n > 10),
       aes(y = n, axis1 = utt_parse, axis2 = next_frame, axis3 = next_next_frame)) +
  geom_alluvium(aes(fill = utt_parse)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  theme(legend.position = "none") 

ggplot(act_sequences %>% filter(n > 80),
       aes(y = n, axis1 = meaning, axis2 = next_act, axis3 = next_next_act)) +
  geom_alluvium(aes(fill = meaning)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  theme(legend.position = "none") 

```



```{r comm_acts_gephi}

comm_act_graph <- sequences %>%
  ungroup() %>%
  mutate(next_speaker = lead(speaker),
         exchange_type = if_else(speaker == "CHI" & next_speaker == "ADU", "child_to_parent",
                                 if_else(speaker == "ADU" & next_speaker == "CHI", "parent_to_child", "repeat"),
                                 "repeat")) %>%
  filter(exchange_type == "child_to_parent" | exchange_type == "parent_to_child") %>%
  rename(this_act = meaning) %>%
  group_by(exchange_type, this_act, next_act) %>%
  count() %>%
  ungroup() %>% 
  group_by(exchange_type) %>%
  complete(this_act, next_act) %>%
  mutate(smoothed = if_else(is.na(n), epsilon, n + epsilon)) %>%
  group_by(exchange_type, this_act) %>%
  mutate(prob = smoothed/sum(smoothed),
         freq = sum(smoothed)) %>%
  ungroup()

distinct_acts <- comm_act_graph %>%
  ungroup() %>%
  select(this_act) %>%
  distinct(this_act) %>%
  rowid_to_column() %>%
  rename(id = rowid)

acts_parent_to_child <- comm_act_graph %>%
  ungroup() %>%
  filter(exchange_type == "parent_to_child") %>%
  select(this_act, next_act, prob, freq) %>%
  left_join(distinct_acts, by = c("this_act" = "this_act")) %>%
  rename(current_act_id = id) %>%
  left_join(distinct_acts, by = c("next_act" = "this_act")) %>%
  rename(next_act_id = id) 

acts_parent_nodes <- distinct_acts %>%
  filter(id %in% acts_parent_to_child$current_act_id | id %in% acts_parent_to_child$next_act_id) %>%
  arrange(id) %>%
  left_join(acts_parent_to_child %>% distinct(this_act, freq)) %>%
  mutate(freq = if_else(is.na(freq), epsilon, freq)) %>%
  rename(Id = id, Label = this_act) 

acts_parent_edges <- acts_parent_to_child %>%
  select(current_act_id, next_act_id, prob) %>%
  arrange(current_act_id, next_act_id) %>%
  rename(Source = current_act_id, Target = next_act_id, Weight = prob)
  
#write_csv(acts_parent_nodes, here("acts_parent_to_child_nodes.csv"))
#write_csv(acts_parent_edges, here("acts_parent_to_child_edges.csv"))

acts_child_to_parent <- comm_act_graph %>%
  ungroup() %>%
  filter(exchange_type == "child_to_parent") %>%
  select(this_act, next_act, prob, freq) %>%
  left_join(distinct_acts, by = c("this_act" = "this_act")) %>%
  rename(current_act_id = id) %>%
  left_join(distinct_acts, by = c("next_act" = "this_act")) %>%
  rename(next_act_id = id) 

acts_child_nodes <- distinct_acts %>%
  filter(id %in% acts_child_to_parent$current_act_id | id %in% acts_child_to_parent$next_act_id) %>%
  left_join(acts_child_to_parent %>% distinct(this_act, freq)) %>%
  mutate(freq = if_else(is.na(freq), epsilon, freq)) %>%
  arrange(id) %>%
  rename(Id = id, Label = this_act)

acts_child_edges <- acts_child_to_parent %>%
  select(current_act_id, next_act_id, prob) %>%
  arrange(current_act_id, next_act_id) %>%
  rename(Source = current_act_id, Target = next_act_id, Weight = prob)

#write_feather(sequences, here("data/ldp_sequences.feather"))
#write_csv(acts_child_nodes, here("acts_child_to_parent_nodes.csv"))
#write_csv(acts_child_edges, here("acts_child_to_parent_edges.csv"))
```

```{r write-child}
#write_csv(child_nodes, here("child_to_parent_nodes.csv"))
#write_csv(child_edges, here("child_to_parent_edges.csv"))
```

```{r frames}
frames_multiple <- frame_freqs %>%
  filter(n > 1)

frame_counts <- sequences %>%
  rename(this_frame = utt_parse) %>%
  filter(this_frame %in% frames_multiple$utt_parse,
         this_frame %in% frames_multiple$utt_parse) %>%
  group_by(this_frame, next_frame) %>%
  count() %>%
  ungroup()

frame_ids <- frame_counts %>%
  select(this_frame) %>%
  rbind(frame_counts %>% select(next_frame) %>% rename(this_frame = next_frame)) %>%
  distinct(this_frame) %>%
  rowid_to_column()

frame_counts <- frame_counts %>%
  left_join(frame_ids, by = c("this_frame" = "this_frame")) %>%
  rename(this_frame_id = rowid) %>%
  left_join(frame_ids, by = c("next_frame" = "this_frame")) %>%
  rename(next_frame_id = rowid)
  

frames_matrix <- sparseMatrix(
  i = frame_counts$this_frame_id,
  j = frame_counts$next_frame_id, 
  x = frame_counts$n
)

clusters <- skmeans(frames_matrix, 15, method='pclust', control=list(verbose=TRUE))
summary(silhouette(clusters))
plot(silhouette(clusters))

regclusters <- kmeans(frames_matrix, 30)

fviz_cluster(clusters)

svd <- irlba(frames_matrix)
pca <- prcomp_irlba(frames_matrix)


pca$x %>% 
  as.data.frame %>% View()
  ggplot(aes(x=PC1,y=PC2)) + geom_point() 
  
  
s <- irlba(frames_matrix, nu = 0, nv=10)
mat_reduced <- as.matrix(frames_matrix %*% s$v)
clust_kmeans <- kmeans(mat_reduced, 10)
fviz_cluster(clust_kmeans, data = mat_reduced)

```

```{r aoas}
comm_act_aoas <- ldp %>%
  filter(speaker == "CHI") %>%
  group_by(child_id, age_months, meaning) %>%
  summarise(earliest_age = min(age_months)) %>%
  ungroup() %>%
  group_by(meaning) %>%
  summarise(aoa = median(age_months))

avg_comm_act_rep <- ldp %>%
  filter(speaker == "CHI") %>%
  group_by(child_id, age_months) %>%
  summarise(num_comm_acts = n_distinct(meaning)) %>%
  ungroup() %>%
  group_by(age_months) %>%
  summarise(avg_comm_acts = mean(num_comm_acts))

comm_act_aoas <- comm_act_aoas %>%
  left_join(avg_comm_act_rep, by = c("aoa" = "age_months"))

comm_act_aoas %>%
  ggplot(aes(x = aoa, y = avg_comm_acts, label = meaning)) + 
  geom_text(position = position_jitter(width = 2, height = 2)) 



frame_aoas <- ldp %>%
  filter(speaker == "CHI") %>%
  group_by(child_id, age_months, utt_parse) %>%
  summarise(earliest_age = min(age_months)) %>%
  ungroup() %>%
  group_by(utt_parse) %>%
  summarise(aoa = median(age_months))

frame_rep <- ldp %>%
  filter(speaker == "CHI") %>%
  group_by(child_id, age_months) %>%
  summarise(num_frames = n_distinct(utt_parse)) %>%
  ungroup() %>%
  group_by(age_months) %>%
  summarise(avg_frames = mean(num_frames))

child_frame_freqs <- ldp %>%
  filter(speaker == "CHI") %>%
  count(utt_parse) 

top_child_frames <- child_frame_freqs %>%
  arrange(desc(n)) %>%
  slice(1:100)
  
frame_aoas <- frame_aoas %>%
  left_join(frame_rep, by = c("aoa" = "age_months")) %>%
  left_join(child_frame_freqs, by = "utt_parse")

# 
# frame_aoas %>%
#   mutate(prop = n/sum(n)) %>%
#   filter(utt_parse %in% top_child_frames$utt_parse) %>%
#   ggplot(aes(x = aoa, y = avg_frames, label = utt_parse, alpha = prop)) + 
#   geom_text(position = position_jitter(width = 3, height = 8), alpha = prop) +
#   geom_smooth()
```